project:
  type: book


book:
  title: "Data Science II with python (Class notes)"
  subtitle: "STAT 303-2"
  author: "Arvind Krishna"
  date: "1/3/2023"
  
  sidebar:
    search: true
    logo: "NU_Stat_logo.png"
    logo-href: "https://statistics.northwestern.edu/"
    
  chapters:
    - index.qmd
    - part: "Linear regression"
      chapters:
        - Lec1_SimpleLinearRegression.ipynb
        - Lec2_MultipleLinearRegression.ipynb
        - Lec3_VariableTransformations_and_Interactions.ipynb
        - Lec4_ModelAssumptions.ipynb
  appendices: 
    - Assignment 1.ipynb
    - Assignment B.ipynb
    - Datasets.ipynb
    - references.qmd  

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



