project:
  type: book
  output-dir: docs



book:
  title: "Data Science II with python (Class notes)"
  subtitle: "STAT 303-2"
  author: "Arvind Krishna"
  date: "1/3/2023"
  
  sidebar:
    search: true
    logo: "NU_Stat_logo.png"
    logo-href: "https://statistics.northwestern.edu/"
    
  chapters:
    - index.qmd
    - Lec1_SimpleLinearRegression.ipynb
    - Lec2_MultipleLinearRegression.ipynb
    - Lec3_VariableTransformations_and_Interactions.ipynb
    - Lec7_logistic_regression.ipynb
    - Lec9_RidgeRegression_Lasso.ipynb
    - Crossvalidation.ipynb
    - Lec5_Potential_issues.ipynb
   

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



