project:
  type: book


book:
  title: "Data Science II with python (Class notes)"
  subtitle: "STAT 303-2"
  author: "Arvind Krishna"
  date: "1/3/2023"
  
  sidebar:
    search: true
    logo: "NU_Stat_logo.png"
    logo-href: "https://statistics.northwestern.edu/"
    
  chapters:
    - index.qmd
    - part: "Linear regression"
      chapters:
        - Lec1_SimpleLinearRegression.ipynb
        - Lec2_MultipleLinearRegression.ipynb
    - part: "Assignments"
      chapters:
        - Assignment 1 (Section 20).ipynb
	- Assignment 1 (Sections 21 & 22).ipynb
	- Assignment 2.ipynb


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



