project:
  type: book
  output-dir: docs



book:
  title: "Data Science II with python (Class notes)"
  subtitle: "STAT 303-2-Sec20&21"
  date: "1/7/2025"
  
  sidebar:
    search: true
    logo: "NU_Stat_logo.png"
    logo-href: "https://statistics.northwestern.edu/"
    
  chapters:
    - index.qmd
    - Lec1_SimpleLinearRegression.ipynb
    - Lec2_MultipleLinearRegression.ipynb
    - Lec3_VariableTransformations_and_Interactions.ipynb
    - Lec7_logistic_regression.ipynb
    - Lec9_RidgeRegression_Lasso.ipynb
    - Crossvalidation.ipynb
    - Lec5_Potential_issues.ipynb
   
  appendices: 
    - Assignment_1_wi25.ipynb
    - Assignment 2.ipynb
    - Datasets.ipynb
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



