project:
  type: book


book:
  title: "Data Science II with python (Class notes)"
  subtitle: "STAT 303-2"
  author: "Arvind Krishna"
  date: "9/20/2022"
  
  sidebar:
    search: true
    logo: "NU_Stat_logo.png"
    logo-href: "https://statistics.northwestern.edu/"
    
  chapters:
    - index.qmd
    - part: "Python"
      chapters:
        - Lec1_SimpleLinearRegression.ipynb
        - Variable_expressions_statements.ipynb
        - Control flow.ipynb
        - data_structures.ipynb
        - classes.ipynb
  appendices: 
    - Assignment 1 (control flow).ipynb
    - Assignment 2 (functions).ipynb
    - Assignment 3 (data structures).ipynb
    - Assignment 4 (classes).ipynb
    - Datasets.ipynb

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



